#version: '3.8'

services:
  # ---------------------------
  # MySQL Database
  # ---------------------------
  mysql:
    image: mysql:8.0
    container_name: dairy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MYFARMER_DB
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ---------------------------
  # Zookeeper (Kafka dependency)
  # ---------------------------
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: dairy_zookeeper
    ports:
      - "2181:2181"
    restart: always

  # ---------------------------
  # Kafka Broker
  # ---------------------------
  kafka:
    image: wurstmeister/kafka
    container_name: dairy_kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "user-events:1:1"
      KAFKA_LOG_RETENTION_HOURS: 12
    depends_on:
      - zookeeper

  # ---------------------------
  # Spring Boot Application
  # ---------------------------
  app:
    build: .
    image: myfarmer-app
    container_name: dairy_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MYFARMER_DB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

volumes:
  mysql_data:
