version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: dairy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MYFARMER_DB
    ports:
      - "3307:3306"   # Expose MySQL on port 3307 of your laptop
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: dairy_zookeeper
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: dairy_kafka
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

volumes:
  mysql_data:
